name: Deploy API to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Publish .NET Project
        run: |
          dotnet publish CareerPathCore.sln --configuration Release --output ./out
      - name: Check Output Directory
        run: ls -la ./out

      - name: Prepare DigitalOcean
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 24.199.121.110
          username: root
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          port: 22
          run: rm -rf /var/www/career-path-api/*
            
      - name: Add DigitalOcean Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 24.199.121.110 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Transfer Output Directory To DigitalOcean
        run: |
          sshpass -p "${{ secrets.DEPLOY_SSH_PASSWORD }}" scp -r ./out/* root@24.199.121.110:/var/www/career-path-api/
  
      - name: Deploy API
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 24.199.121.110
          username: root
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          port: 22
          script: |
            # Kill any running instance of the API
            pkill -f "dotnet" || true
        
            # Start the new API instance with full detachment
            setsid nohup dotnet /var/www/career-path-api/CareerPathCore.API.dll > /var/www/career-path-api/app.log 2>&1 < /dev/null &
        
            # Wait a moment to ensure the process starts
            sleep 5
        
            # Check if the API process is running
            pgrep -f "dotnet" > /dev/null && echo "API is running" || (echo "API failed to start" && exit 1)
        
            # Check if the application is listening on the correct port (e.g., 5000)
            netstat -tuln | grep 5000 || (echo "API is not listening on port 5000" && exit 1)
        
        
