name: Deploy API to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Publish .NET Project
        run: |
          dotnet publish CareerPathCore.sln --configuration Release --output ./out
      - name: Check Output Directory
        run: ls -la ./out

      - name: Prepare DigitalOcean for Transfer
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 24.199.121.110
          username: root
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          port: 22
          debug: true
          script: |
            # Ensure deployment directory exists and is clean
            mkdir -p /var/www/career-path-api
            rm -rf /var/www/career-path-api/*
  
      - name: Transfer Output Directory To DigitalOcean
        run: | 
            scp -r ./out/* root@24.199.121.110:/var/www/career-path-api/
  
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 24.199.121.110
          username: root
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          port: 22
          debug: true
          script: |
            # Kill any running instance of the API
            pkill -f "dotnet CareerPathCore.API.dll" || true
  
            # Start the new API instance
            nohup dotnet /var/www/career-path-api/CareerPathCore.API.dll > /var/www/career-path-api/app.log 2>&1 &

