name: Deploy API to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Publish .NET Project
        run: |
          dotnet publish CareerPathCore.sln --configuration Release --output ./out
      - name: Check Output Directory
        run: ls -la ./out

      - name: Prepare DigitalOcean
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 24.199.121.110
          username: root
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          port: 22
          run: rm -rf /var/www/career-path-api/*
            
      - name: Add DigitalOcean Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 24.199.121.110 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Transfer Output Directory To DigitalOcean
        run: |
          sshpass -p "${{ secrets.DEPLOY_SSH_PASSWORD }}" scp -r ./out/* root@24.199.121.110:/var/www/career-path-api/
  
      - name: Deploy API
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 24.199.121.110
          username: root
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          port: 22
          script: |
            # STOP old API service if it exists
            systemctl stop careerpath-api || true
            systemctl disable careerpath-api || true
        
            # RELOAD systemd and start the service
            systemctl daemon-reload
            systemctl enable careerpath-api
            systemctl start careerpath-api
        
            # Wait a moment to ensure the process starts
            sleep 5
        
            # Check if the API process is running
            systemctl status careerpath-api
        
        
